apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://azcluster-dns-c5caac81.hcp.southindia.azmk8s.io:443
  name: azcluster
- cluster:
    insecure-skip-tls-verify: true
    server: https://172.16.70.57:8001
  name: ilon1
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://sumitakscl-sumit-1325be-b1b9c6ea.hcp.southindia.azmk8s.io:443
  name: sumitakscluster
contexts:
- context:
    cluster: azcluster
    user: clusterUser_sumit_azcluster
  name: azcluster
- context:
    cluster: ilon1
    namespace: namespace03
    user: user3
  name: ilon1-context
- context:
    cluster: ""
    namespace: namespace3
    user: ""
  name: mycluster-context
- context:
    cluster: sumitakscluster
    user: clusterUser_sumit_sumitakscluster
  name: sumitakscluster
current-context: ilon1-context
kind: Config
preferences: {}
users:
- name: clusterUser_sumit_azcluster
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: a49f2ce1550fe9628c45242db56772b5
- name: clusterUser_sumit_sumitakscluster
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    token: 2dbc7edb2e6c143914aaaaeb36125af9
- name: ilon1-user
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiNDBjOWUxYjY0MGNiYzg4ZDM2YTZmNWUyYjIxNzcyNWRhMDg1Nzc5YiIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjMiLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1OTEzMzE3NywiaWF0IjoxNTU5MTA0Mzc3LCJzdWIiOiJ1c2VyMyIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.XOA2-tp3rILAff_iWT9d5nUa_oFkoqpOdTGyrnykmSmRmrAcoUQAl6fM1zCe4qAI8rS41e1abNcEj2zt_akyQJen_N1-kpiFn-ujE6fTs1r2_yWcNY7n6SO9auexXqMocOeIiOnaKtvEdRUifV802m8uxOkwcoel4AKo55iihVoNme0vjzuErCRLlU6Xj7vw_CO4ih_SG2n8G183LBx5tcMEK8xViTJFh1-zAcjbgrXmmKKS-ZK9Uzx0tS0ZlF18h4Jc6Lm2_HhA845LrzBPOZwfAI-ttcH2qf17R3LSEo4WqLf31D2RbQOQZf2kbSnN7FnYrhqB6uoVgU7aVQsqlg
- name: user3
  user:
    token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdF9oYXNoIjoiZDBkNmQ3MzcxODhkNDI4OTdiMTg1MjVjZWNhM2NlMTRkYWExNDM2NyIsInJlYWxtTmFtZSI6ImN1c3RvbVJlYWxtIiwidW5pcXVlU2VjdXJpdHlOYW1lIjoidXNlcjMiLCJpc3MiOiJodHRwczovL2lsb24xLmljcDo5NDQzL29pZGMvZW5kcG9pbnQvT1AiLCJhdWQiOiJkMGIwOGIzZGQxYWUzM2FlNWRhNTE1YzQwZGRhYWZlYyIsImV4cCI6MTU1OTE1MzYyMywiaWF0IjoxNTU5MTI0ODIzLCJzdWIiOiJ1c2VyMyIsInRlYW1Sb2xlTWFwcGluZ3MiOlsic3lzdGVtOm1hc3RlcnMiXX0.CmOp_QNpL7x3sDS4cKHqjg05EtiyBDkd2C7UaXWNxYKK-FTG8CpFiOAl2jCEo_qtZ0y9Ktl-LuBgb1BBQVJGd_G7Tm5bw09EkdMN0B9rm130y6B804hDdkbQvLFgqicHpX4ZoeJSXe412zFGVhiXex8BOuWg84YAAiANjXEHz1bONXQ611keek33WMcNE-0BSP73v09WesBxIYf8AfOwN2uZp5AC3NZxjhraR-tBuzGhbGHTOEMWqY5l3IU4IRhNlD81MiR1YPwy1OV2XsX9xIrocSW3UX9d2HadXcEQxmKMkTJIj8xvvyU36U058OYr3NvT93BQSzPF7WDDkZ8tjw
